
services:
  irc-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "22200:22200"
    # volumes:
    #   - ./config:/app/config
    #   - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - irc_net
    environment:
      - SERVER_NAME=WeUseArch
      - MAX_CLIENTS=100
      # - HOST=
    cap_add:
      - NET_ADMIN
    # Ensure host networking visibility
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "22200"]
      interval: 30s
      timeout: 10s
      retries: 3

  builder:
    build:
      context: .
      dockerfile: Dockerfile
    command: make
    volumes:
      - .:/app
    working_dir: /app
    networks:
      - irc_net
    profiles:
      - build

networks:
  irc_net:
    driver: bridge
