#!/bin/bash

# Default Configurations
DEFAULT_SUMMARY_FILE="testSummary.md"
DEFAULT_PORT=22200
DEFAULT_PASSWORD="Alilepro135!"
DEFAULT_SERVER_BINARY="./bin/irc-server"
DEFAULT_TIMEOUT=5
DEFAULT_LOG_FILE="irc.log"
DEFAULT_MAX_PARALLEL_TESTS=5

# Runtime Configuration
SUMMARY_FILE=$DEFAULT_SUMMARY_FILE
PORT=$DEFAULT_PORT
PASSWORD=$DEFAULT_PASSWORD
SERVER_BINARY=$DEFAULT_SERVER_BINARY
TIMEOUT=$DEFAULT_TIMEOUT
LOG_FILE=$DEFAULT_LOG_FILE
MAX_PARALLEL_TESTS=$DEFAULT_MAX_PARALLEL_TESTS

# Test Counters
TOTAL_TESTS=0
PASSED_TESTS=0
FAILED_TESTS=0
SKIPPED_TESTS=0
TEST_START_TIME=""
TEST_END_TIME=""

# State Flags
DEBUG=0
VERBOSE=0
QUIET=0
NO_COLOR=0
SKIP_CLEANUP=0
CUSTOM_TESTS=""

# Misc
TIME=$(date -u '+%Y-%m-%d %H:%M:%S UTC')

# Array to store failed tests
declare -a FAILED_TESTS_ARRAY
